In [1]:
import pandas as pd

url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=TWEXBGSMTH"

usd_index = pd.read_csv(url)

usd_index.head()

  observation_date  TWEXBGSMTH
0       2006-01-01    100.0000
1       2006-02-01    100.2112
2       2006-03-01    100.4281
3       2006-04-01     99.7435
4       2006-05-01     97.5118

In [7]:
usd_index = usd_index.rename(
    columns={
        "observation_date": "month",
        "TWEXBGSMTH": "usd_index"
    }
)

In [8]:
usd_index.head()

        month  usd_index
0  2006-01-01   100.0000
1  2006-02-01   100.2112
2  2006-03-01   100.4281
3  2006-04-01    99.7435
4  2006-05-01    97.5118

In [9]:
usd_index["month"] = pd.to_datetime(
    usd_index["month"]
).dt.to_period("M")

In [10]:
usd_index.head()

     month  usd_index
0  2006-01   100.0000
1  2006-02   100.2112
2  2006-03   100.4281
3  2006-04    99.7435
4  2006-05    97.5118

In [12]:
usd_index.to_csv("usd_index.csv" , index = False)